print ("Programa para calcular la suma de 2 números")
n1 = input ("Escribe el primero:")
n2 = input ("Escribe el segundo:")
suma = eval (n1)+ eval (n2)
print ("La suma ye:", n1, "y", n2, "es", suma)